// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package main

import (
	"time"
)

type Student struct {
	ID          int64
	Fname       string
	Lname       string
	DateOfBirth time.Time
	Email       string
	Address     string
	Gender      string
}
